var n = 1451;
var f = 3.1416;
var nn = Number(45);
var NN = Number('50.50');
console.log(nn);
console.log(NN);
console.log(Number.parseFloat(nn));
console.log(Number.parseInt(NN));
console.log(Number.MAX_VALUE);
console.log(Number.MIN_VALUE);
console.log(1/0);
console.log('abc' * 10);